#ifndef DRIVERSCONTAINER_CONFIG_H
#define DRIVERSCONTAINER_CONFIG_H

#define MOTOR_PWM_PIN			23
#define MOTOR_ENABLE_PIN		25
#define MOTOR_DIRECTION_PIN		22

#define RIGHT_BUTTON_PIN		19
#define LEFT_BUTTON_PIN			20

#endif //DRIVERSCONTAINER_CONFIG_H
